name: test
on:
  - push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install ecs-cli
        uses: ./
        with:
          version: "v1.21.0"
      - run: ecs-cli --version

  test-shell:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install ecs-cli
        run: bash entrypoint.sh
      - run: ecs-cli --version
